### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by isymkz44** [isymkz44/furima-38736#20]
・FURIMAアプリのURL
https://furima-38736.onrender.com/

・Basic認証
ユーザー名：admin
パスワード：2222

・出品者用のアカウント
メールアドレス：test1@123
パスワード：test111

・購入者用のアカウント
メールアドレス：test2@123
パスワード：test222

**Comment by ghost** [comment]
@isymkz44 さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
**商品出品機能の確認**
- [ ] **発送元の地域は、「---」と47都道府県の合計48項目が表示されるようにしましょう（--- は初期値として設定すること）**
 現在、初期値が「--」となっておりますので、「---」と表示されるようにしましょう。
<img width="411" alt="スクリーンショット 2023-01-17 16 18 10" src="https://user-images.githubusercontent.com/116065064/212836855-f64bb736-c875-4493-8d4d-c13b2a11ac10.png">



**商品出品機能の確認**
- [ ] **発送までの日数は、「---、1~2日で発送、2~3日で発送、4~7日で発送」の4項目が表示されるようにしましょう（--- は初期値として設定すること）**
現在、「2~3日で発送」の「〜」が大文字になっておりますので、半角で表示されるようにしましょう。
<img width="371" alt="スクリーンショット 2023-01-17 16 17 31" src="https://user-images.githubusercontent.com/116065064/212836873-ffdaf6d1-12d8-48c0-9492-2aca45d433da.png">



修正が完了しましたら、一度ご自身の本番環境で正しく挙動されているか確認してみましょう。
挙動確認を行い、修正内容が反映されていることを確認できましたら再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by isymkz44** [comment]
修正いてしました。
ご確認のほどよろしくお願い致します。

**Comment by maru2628** [comment]
@isymkz44 さん、ご提出ありがとうございます‼︎
正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
別途、最終課題の案内をチャンネルに送らせて頂きます。
今しばらくお待ちください。

**Comment by ghost** [comment]
@isymkz44 さん、最終課題「FURIMA」の開発、お疲れ様です。

ご提出いただいたアプリケーションについて、正常に動作することを確認いたしました。
達成要件を満たしましたので、完了認定（LGTM）とさせていただきます。おめでとうございます。

`本メッセージ内で、今後の学習についてご案内しています。必ず確認するようにしてください。`

_※ スタッフ側で実施した動作確認は必須機能についてのみです。追加機能についての動作確認は実施しておりません。追加機能を実装した場合は想定通りの挙動となっているか自分自身で確認をお願い致します。_
_※ Github上の最終課題の履歴はここまで頑張ってきたことの証となります。削除せず大切に保管するようにしましょう。_

------------------------------------------------------------------------------------------
◆ 今後の流れについてのご案内（※詳細は下記リンクのガイダンス資料参照）
------------------------------------------------------------------------------------------
◎この後の期間では、以下のアクションが必要となります。
・最終課題説明文の作成・提出
・FURIMAへの追加機能の実装 または オリジナルアプリ開発
・上記の開発に関する要件定義書の提出
・履歴書と職務経歴書の作成・提出（転職サポートありの方）
・学習成果発表会の準備

◎下記リンク先の「**追加実装・オリジナルアプリ開発 ガイダンス資料**」を必ずご確認ください。
**https://master.tech-camp.in/v2/curriculums/7839**

------------------------------------------------------------------------------------------
◆ さいごに
------------------------------------------------------------------------------------------
◎ガイダンス資料を確認した上で、今後の流れについて不明点がございましたら、担当ライフコーチまでご相談ください。

◎いよいよ卒業までのラストスパートです。これまで頑張ってきたことをフル活用して、最大限の受講成果につなげていきましょう。
![最終課題LGTM](https://user-images.githubusercontent.com/116065064/212840814-c794fc87-f9d8-47e7-8649-acaa9d02ca04.png)
